const $=id=>document.getElementById(id);
const els={templateInput:$('templateInput'),templateDrop:$('templateDrop'),templateMeta:$('templateMeta'),templateState:$('templateState'),dataInput:$('dataInput'),dataDrop:$('dataDrop'),dataMeta:$('dataMeta'),dataState:$('dataState'),downloadTemplateButton:$('downloadTemplateButton'),sampleButton:$('sampleButton'),dataPreviewPanel:$('dataPreviewPanel'),rowCountText:$('rowCountText'),columnChips:$('columnChips'),dataTable:$('dataTable'),editorSection:$('editorSection'),fieldButtons:$('fieldButtons'),fieldControls:$('fieldControls'),selectedColumn:$('selectedColumn'),fontSelect:$('fontSelect'),weightSelect:$('weightSelect'),fontSize:$('fontSize'),fontColor:$('fontColor'),alignSelect:$('alignSelect'),maxWidth:$('maxWidth'),autoFit:$('autoFit'),removeFieldButton:$('removeFieldButton'),participantSelect:$('participantSelect'),prevParticipant:$('prevParticipant'),nextParticipant:$('nextParticipant'),previewStatus:$('previewStatus'),previewCanvas:$('previewCanvas'),overlayLayer:$('overlayLayer'),exportPanel:$('exportPanel'),exportSummary:$('exportSummary'),statusBox:$('statusBox'),downloadCurrentButton:$('downloadCurrentButton'),generateZipButton:$('generateZipButton'),generatePdfButton:$('generatePdfButton')};

const GOOGLE_FONTS=[
 {name:'Inter',weights:[400,500,600,700]},
 {name:'Poppins',weights:[400,500,600,700]},
 {name:'Montserrat',weights:[400,500,600,700]},
 {name:'Open Sans',weights:[400,600,700]},
 {name:'Playfair Display',weights:[400,500,600,700]},
 {name:'Cormorant Garamond',weights:[400,500,600,700]},
 {name:'Libre Baskerville',weights:[400,700]},
 {name:'Lora',weights:[400,500,600,700]},
 {name:'Cinzel',weights:[400,500,600,700]},
 {name:'DM Serif Display',weights:[400]},
 {name:'Great Vibes',weights:[400]},
 {name:'Allura',weights:[400]},
 {name:'Dancing Script',weights:[400,500,600,700]}
];

const state={template:null,rows:[],columns:[],fields:[],selectedFieldId:null,previewIndex:0};
const ctx=els.previewCanvas.getContext('2d');
const uid=()=>crypto.randomUUID?.()||`f-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeName=s=>String(s||'certificate').trim().replace(/[^a-z0-9-_]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,80)||'certificate';

function setStatus(message,type='neutral'){els.statusBox.className=`status-box is-${type}`;els.statusBox.textContent=message}
function fontCssUrl(name,weights){const family=name.trim().replace(/ /g,'+');return `https://fonts.googleapis.com/css2?family=${family}:wght@${weights.join(';')}&display=swap`}
async function loadFont(name,weight=400){if(!name)return;const id=`gf-${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`;if(!document.getElementById(id)){const meta=GOOGLE_FONTS.find(f=>f.name===name)||{weights:[400]};const link=document.createElement('link');link.id=id;link.rel='stylesheet';link.href=fontCssUrl(name,meta.weights);document.head.appendChild(link)}try{await document.fonts.load(`${weight} 32px "${name}"`);await document.fonts.ready}catch{}}
function populateFonts(){els.fontSelect.innerHTML=GOOGLE_FONTS.map(f=>`<option value="${esc(f.name)}">${esc(f.name)}</option>`).join('');updateWeightOptions(GOOGLE_FONTS[0].name)}
function updateWeightOptions(name,selected=400){const meta=GOOGLE_FONTS.find(f=>f.name===name)||GOOGLE_FONTS[0];els.weightSelect.innerHTML=meta.weights.map(w=>`<option value="${w}" ${Number(selected)===w?'selected':''}>${w}</option>`).join('')}

async function loadTemplate(file){if(!file)return;try{let canvas=document.createElement('canvas');let c=canvas.getContext('2d');if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){els.templateState.textContent='Reading PDF…';const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const page=await pdf.getPage(1);const viewport=page.getViewport({scale:2});canvas.width=Math.round(viewport.width);canvas.height=Math.round(viewport.height);c=canvas.getContext('2d');await page.render({canvasContext:c,viewport}).promise}else{const bitmap=await createImageBitmap(file);canvas.width=bitmap.width;canvas.height=bitmap.height;c.drawImage(bitmap,0,0);bitmap.close?.()}
 const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));const img=await createImageBitmap(blob);state.template={image:img,width:canvas.width,height:canvas.height,name:file.name};els.templateMeta.classList.remove('hidden');els.templateMeta.innerHTML=`<strong>${esc(file.name)}</strong><span>${canvas.width} × ${canvas.height}px</span>`;els.templateState.textContent='Ready';renderWorkspace()}catch(err){console.error(err);els.templateState.textContent='Error';alert('Could not read that certificate template. Try PNG, JPG, WebP, or a standard PDF.') }}

function normalizeRows(rows){const clean=rows.filter(r=>r&&typeof r==='object'&&Object.values(r).some(v=>String(v??'').trim()!==''));return clean.slice(0,500).map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[String(k).trim()||'Column',v??''])))}
function setRows(rows,source='Participant data'){state.rows=normalizeRows(rows);state.columns=state.rows.length?Object.keys(state.rows[0]):[];state.fields=state.fields.filter(f=>state.columns.includes(f.column));state.selectedFieldId=null;state.previewIndex=0;els.dataState.textContent=state.rows.length?'Ready':'Empty';els.dataMeta.classList.remove('hidden');els.dataMeta.innerHTML=`<strong>${esc(source)}</strong><span>${state.rows.length} participant${state.rows.length===1?'':'s'} · ${state.columns.length} column${state.columns.length===1?'':'s'}</span>`;renderDataPreview();renderWorkspace()}
async function loadData(file){if(!file)return;try{if(typeof XLSX==='undefined')throw new Error('XLSX library unavailable');const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false});const sheet=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(sheet,{defval:''});if(!rows.length)throw new Error('No rows');setRows(rows,file.name)}catch(err){console.error(err);alert('Could not read that spreadsheet. Make sure the first row contains column headers.')}}
function downloadExcelTemplate(){const rows=[{name:'Andi Saputra',certificate_no:'CERT-001',company:'PT Example',role:'Participant',event:'Creative Workshop',date:'3 Oct 2026'},{name:'Budi Santoso',certificate_no:'CERT-002',company:'CV Sample',role:'Participant',event:'Creative Workshop',date:'3 Oct 2026'}];const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:26},{wch:18},{wch:24},{wch:18},{wch:24},{wch:16}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Participants');XLSX.writeFile(wb,'astakula-certificate-participants-template.xlsx')}
function useSampleData(){setRows([{name:'Andi Saputra',certificate_no:'CERT-001',company:'PT Example',role:'Participant',event:'Creative Workshop',date:'3 Oct 2026'},{name:'Budi Santoso',certificate_no:'CERT-002',company:'CV Sample',role:'Participant',event:'Creative Workshop',date:'3 Oct 2026'},{name:'Citra Dewi',certificate_no:'CERT-003',company:'Astakula',role:'Speaker',event:'Creative Workshop',date:'3 Oct 2026'}],'Sample data')}

function renderDataPreview(){if(!state.rows.length){els.dataPreviewPanel.hidden=true;return}els.dataPreviewPanel.hidden=false;els.rowCountText.textContent=`${state.rows.length} participant${state.rows.length===1?'':'s'}`;els.columnChips.innerHTML=state.columns.map(c=>`<span>${esc(c)}</span>`).join('');const preview=state.rows.slice(0,5);els.dataTable.innerHTML=`<thead><tr>${state.columns.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${preview.map(r=>`<tr>${state.columns.map(c=>`<td>${esc(r[c])}</td>`).join('')}</tr>`).join('')}</tbody>`}
function renderFieldButtons(){els.fieldButtons.innerHTML=state.columns.map(c=>`<button type="button" class="field-add-button" data-add-field="${esc(c)}"><span>+</span><strong>${esc(c)}</strong></button>`).join('');els.fieldButtons.querySelectorAll('[data-add-field]').forEach(b=>b.addEventListener('click',()=>addField(b.dataset.addField)))}
function addField(column){if(!state.template)return;const field={id:uid(),column,x:.5,y:.5,font:'Cormorant Garamond',weight:600,size:Math.max(24,Math.round(state.template.width*.04)),color:'#161616',align:'center',maxWidth:Math.round(state.template.width*.7),autoFit:true};state.fields.push(field);state.selectedFieldId=field.id;loadFont(field.font,field.weight).then(()=>drawPreview());renderFieldControls();renderOverlays();updateExportState();drawPreview()}
function selectedField(){return state.fields.find(f=>f.id===state.selectedFieldId)||null}
function renderFieldControls(){const f=selectedField();els.fieldControls.classList.toggle('is-disabled',!f);for(const el of [els.fontSelect,els.weightSelect,els.fontSize,els.fontColor,els.alignSelect,els.maxWidth,els.autoFit,els.removeFieldButton])el.disabled=!f;if(!f){els.selectedColumn.value='';return}els.selectedColumn.value=f.column;els.fontSelect.value=f.font;updateWeightOptions(f.font,f.weight);els.fontSize.value=f.size;els.fontColor.value=f.color;els.alignSelect.value=f.align;els.maxWidth.value=f.maxWidth;els.autoFit.checked=f.autoFit}

function renderWorkspace(){const ready=state.template&&state.rows.length;els.editorSection.hidden=!ready;els.exportPanel.hidden=!ready;if(!ready)return;els.previewCanvas.width=state.template.width;els.previewCanvas.height=state.template.height;renderFieldButtons();els.participantSelect.innerHTML=state.rows.map((r,i)=>`<option value="${i}">${i+1}. ${esc(displayName(r,i))}</option>`).join('');els.participantSelect.value=String(state.previewIndex);renderFieldControls();drawPreview();requestAnimationFrame(renderOverlays);updateExportState()}
function displayName(row,i){const preferred=['name','nama','nama peserta','participant','recipient'];const key=state.columns.find(c=>preferred.includes(c.toLowerCase()));return key?String(row[key]||`Participant ${i+1}`):String(row[state.columns[0]]||`Participant ${i+1}`)}
async function fitFont(context,text,f){let size=Number(f.size)||52;const min=Math.max(8,Math.min(20,size));context.font=`${f.weight} ${size}px "${f.font}"`;if(f.autoFit){while(size>min&&context.measureText(text).width>f.maxWidth){size-=1;context.font=`${f.weight} ${size}px "${f.font}"`}}return size}
async function drawOnCanvas(canvas,row){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.drawImage(state.template.image,0,0,canvas.width,canvas.height);for(const f of state.fields){await loadFont(f.font,f.weight);const text=String(row?.[f.column]??'');const size=await fitFont(c,text,f);c.font=`${f.weight} ${size}px "${f.font}"`;c.fillStyle=f.color;c.textAlign=f.align;c.textBaseline='middle';c.fillText(text,f.x*canvas.width,f.y*canvas.height,f.maxWidth)}return canvas}
async function drawPreview(){if(!state.template||!state.rows.length)return;els.previewStatus.textContent='Rendering…';await drawOnCanvas(els.previewCanvas,state.rows[state.previewIndex]);els.previewStatus.textContent=`${state.previewIndex+1} / ${state.rows.length}`}
function renderOverlays(){if(els.editorSection.hidden||!state.template)return;const rect=els.previewCanvas.getBoundingClientRect();const stageRect=els.certificateStage.getBoundingClientRect();els.overlayLayer.style.left=`${rect.left-stageRect.left}px`;els.overlayLayer.style.top=`${rect.top-stageRect.top}px`;els.overlayLayer.style.width=`${rect.width}px`;els.overlayLayer.style.height=`${rect.height}px`;els.overlayLayer.innerHTML=state.fields.map(f=>{const selected=f.id===state.selectedFieldId;return `<button type="button" class="field-overlay ${selected?'is-selected':''}" data-field-id="${f.id}" style="left:${f.x*100}%;top:${f.y*100}%;max-width:${Math.min(90,(f.maxWidth/state.template.width)*100)}%"><span>${esc(state.rows[state.previewIndex]?.[f.column]??f.column)}</span></button>`}).join('');els.overlayLayer.querySelectorAll('[data-field-id]').forEach(el=>{el.addEventListener('pointerdown',startDrag);el.addEventListener('click',()=>{state.selectedFieldId=el.dataset.fieldId;renderFieldControls();renderOverlays()})})}
function startDrag(e){e.preventDefault();state.selectedFieldId=e.currentTarget.dataset.fieldId;renderFieldControls();const f=selectedField();const layerRect=els.overlayLayer.getBoundingClientRect();const move=ev=>{f.x=Math.max(0,Math.min(1,(ev.clientX-layerRect.left)/layerRect.width));f.y=Math.max(0,Math.min(1,(ev.clientY-layerRect.top)/layerRect.height));renderOverlays();drawPreview()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function updateExportState(){const ready=state.template&&state.rows.length&&state.fields.length;els.exportSummary.textContent=`${state.rows.length} recipient${state.rows.length===1?'':'s'} · ${state.fields.length} field${state.fields.length===1?'':'s'}`;for(const b of [els.downloadCurrentButton,els.generateZipButton,els.generatePdfButton])b.disabled=!ready;setStatus(ready?'Ready to generate certificates.':'Add at least one dynamic field before generating the batch.',ready?'success':'neutral')}
function removeSelectedField(){const id=state.selectedFieldId;if(!id)return;state.fields=state.fields.filter(f=>f.id!==id);state.selectedFieldId=null;renderFieldControls();renderOverlays();drawPreview();updateExportState()}
function updateSelected(prop,value){const f=selectedField();if(!f)return;f[prop]=value;drawPreview();renderOverlays()}

async function canvasForRow(row){const canvas=document.createElement('canvas');canvas.width=state.template.width;canvas.height=state.template.height;await drawOnCanvas(canvas,row);return canvas}
function canvasBlob(canvas,type='image/png',quality=.95){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Canvas export failed')),type,quality))}
async function downloadCurrent(){if(!state.fields.length)return;setStatus('Rendering current certificate…');const canvas=await canvasForRow(state.rows[state.previewIndex]);const blob=await canvasBlob(canvas);downloadBlob(blob,`${safeName(displayName(state.rows[state.previewIndex],state.previewIndex))}-certificate.png`);setStatus('Current certificate downloaded.','success')}
async function generateZip(){if(!state.fields.length)return;try{setButtonsBusy(true);const zip=new JSZip();for(let i=0;i<state.rows.length;i++){setStatus(`Rendering ${i+1} of ${state.rows.length} certificates…`);const canvas=await canvasForRow(state.rows[i]);const blob=await canvasBlob(canvas);zip.file(`${String(i+1).padStart(3,'0')}-${safeName(displayName(state.rows[i],i))}.png`,blob)}setStatus('Packaging ZIP…');const out=await zip.generateAsync({type:'blob'});downloadBlob(out,'astakula-certificates.zip');setStatus(`${state.rows.length} certificates generated as PNG ZIP.`,'success')}catch(err){console.error(err);setStatus('Could not generate the ZIP. Try a smaller batch.','error')}finally{setButtonsBusy(false)}}
async function generatePdf(){if(!state.fields.length)return;try{setButtonsBusy(true);const {jsPDF}=window.jspdf;let pdf=null;for(let i=0;i<state.rows.length;i++){setStatus(`Rendering PDF page ${i+1} of ${state.rows.length}…`);const canvas=await canvasForRow(state.rows[i]);const landscape=canvas.width>=canvas.height;const pageW=landscape?297:210;const pageH=landscape?210:297;if(!pdf)pdf=new jsPDF({orientation:landscape?'landscape':'portrait',unit:'mm',format:'a4',compress:true});else pdf.addPage('a4',landscape?'landscape':'portrait');const ratio=Math.min(pageW/canvas.width,pageH/canvas.height);const w=canvas.width*ratio,h=canvas.height*ratio;pdf.addImage(canvas.toDataURL('image/jpeg',.92),'JPEG',(pageW-w)/2,(pageH-h)/2,w,h,undefined,'FAST')}pdf.save('astakula-certificates.pdf');setStatus(`${state.rows.length} certificates generated as a PDF.`,'success')}catch(err){console.error(err);setStatus('Could not generate the PDF. Try a smaller batch.','error')}finally{setButtonsBusy(false)}}
function setButtonsBusy(busy){for(const b of [els.downloadCurrentButton,els.generateZipButton,els.generatePdfButton])b.disabled=busy}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}

function setupDrop(drop,input,handler){['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('is-dragging')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('is-dragging')}));drop.addEventListener('drop',e=>handler(e.dataTransfer.files?.[0]));input.addEventListener('change',()=>handler(input.files?.[0]))}

els.downloadTemplateButton.addEventListener('click',downloadExcelTemplate);els.sampleButton.addEventListener('click',useSampleData);setupDrop(els.templateDrop,els.templateInput,loadTemplate);setupDrop(els.dataDrop,els.dataInput,loadData);els.participantSelect.addEventListener('change',()=>{state.previewIndex=Number(els.participantSelect.value)||0;drawPreview();renderOverlays()});els.prevParticipant.addEventListener('click',()=>{state.previewIndex=(state.previewIndex-1+state.rows.length)%state.rows.length;els.participantSelect.value=String(state.previewIndex);drawPreview();renderOverlays()});els.nextParticipant.addEventListener('click',()=>{state.previewIndex=(state.previewIndex+1)%state.rows.length;els.participantSelect.value=String(state.previewIndex);drawPreview();renderOverlays()});els.removeFieldButton.addEventListener('click',removeSelectedField);els.fontSelect.addEventListener('change',async()=>{const f=selectedField();if(!f)return;f.font=els.fontSelect.value;updateWeightOptions(f.font,400);f.weight=Number(els.weightSelect.value);await loadFont(f.font,f.weight);drawPreview();renderOverlays()});els.weightSelect.addEventListener('change',()=>updateSelected('weight',Number(els.weightSelect.value)));els.fontSize.addEventListener('input',()=>updateSelected('size',Math.max(8,Number(els.fontSize.value)||8)));els.fontColor.addEventListener('input',()=>updateSelected('color',els.fontColor.value));els.alignSelect.addEventListener('change',()=>updateSelected('align',els.alignSelect.value));els.maxWidth.addEventListener('input',()=>updateSelected('maxWidth',Math.max(40,Number(els.maxWidth.value)||40)));els.autoFit.addEventListener('change',()=>updateSelected('autoFit',els.autoFit.checked));els.downloadCurrentButton.addEventListener('click',downloadCurrent);els.generateZipButton.addEventListener('click',generateZip);els.generatePdfButton.addEventListener('click',generatePdf);window.addEventListener('resize',renderOverlays);

populateFonts();loadFont('Cormorant Garamond',600);updateExportState();
