const input=document.getElementById('sourceInput');const dropZone=document.getElementById('dropZone');const preview=document.getElementById('sourcePreview');const previewWrap=document.getElementById('sourcePreviewWrap');const preset=document.getElementById('preset');const slides=document.getElementById('slides');const fit=document.getElementById('fit');const format=document.getElementById('format');const quality=document.getElementById('quality');const qualityValue=document.getElementById('qualityValue');const splitButton=document.getElementById('splitButton');const clearButton=document.getElementById('clearButton');const downloadAllButton=document.getElementById('downloadAllButton');const results=document.getElementById('results');const statusBox=document.getElementById('statusBox');let sourceFile=null;let sourceUrl='';let generated=[];
const presets={portrait:[1080,1350],square:[1080,1080],landscape:[1080,566]};
function setStatus(message){statusBox.textContent=message}
function revokeGenerated(){generated.forEach(item=>URL.revokeObjectURL(item.url));generated=[];results.innerHTML='';downloadAllButton.disabled=true}
function resetSource(){if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceFile=null;sourceUrl='';preview.removeAttribute('src');previewWrap.hidden=true;input.value='';revokeGenerated();setStatus('Choose one image to begin.')}
function validImage(file){return file&&file.type.startsWith('image/')&&file.size<=30*1024*1024}
async function setSource(file){if(!validImage(file)){setStatus('Choose an image file up to 30 MB.');return}resetSource();sourceFile=file;sourceUrl=URL.createObjectURL(file);preview.src=sourceUrl;preview.alt=`Preview of ${file.name}`;previewWrap.hidden=false;await preview.decode().catch(()=>{});setStatus(`${file.name} ready · ${preview.naturalWidth} × ${preview.naturalHeight}px`)}
input.addEventListener('change',()=>setSource(input.files?.[0]));dropZone.addEventListener('dragover',e=>{e.preventDefault();dropZone.classList.add('is-dragging')});dropZone.addEventListener('dragleave',()=>dropZone.classList.remove('is-dragging'));dropZone.addEventListener('drop',e=>{e.preventDefault();dropZone.classList.remove('is-dragging');setSource(e.dataTransfer.files?.[0])});document.addEventListener('paste',e=>{const file=[...(e.clipboardData?.files||[])].find(item=>item.type.startsWith('image/'));if(file)setSource(file)});quality.addEventListener('input',()=>qualityValue.textContent=`${quality.value}%`);clearButton.addEventListener('click',resetSource);
function drawFit(ctx,img,x,y,w,h,mode){const scale=mode==='contain'?Math.min(w/img.naturalWidth,h/img.naturalHeight):Math.max(w/img.naturalWidth,h/img.naturalHeight);const dw=img.naturalWidth*scale,dh=img.naturalHeight*scale;ctx.drawImage(img,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
function toBlob(canvas,mime,q){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Export failed.')),mime,q))}
function extensionFor(mime){return mime==='image/jpeg'?'jpg':mime==='image/webp'?'webp':'png'}
async function splitImage(){if(!sourceFile||!preview.naturalWidth){setStatus('Choose an image first.');return}splitButton.disabled=true;revokeGenerated();try{const [slideW,slideH]=presets[preset.value];const count=Math.max(2,Math.min(10,Number(slides.value)||2));slides.value=count;const full=document.createElement('canvas');full.width=slideW*count;full.height=slideH;const ctx=full.getContext('2d',{alpha:false});ctx.fillStyle='#ffffff';ctx.fillRect(0,0,full.width,full.height);drawFit(ctx,preview,0,0,full.width,full.height,fit.value);const mime=format.value;const q=Number(quality.value)/100;for(let i=0;i<count;i++){const part=document.createElement('canvas');part.width=slideW;part.height=slideH;const pctx=part.getContext('2d',{alpha:mime==='image/png'});pctx.drawImage(full,i*slideW,0,slideW,slideH,0,0,slideW,slideH);const blob=await toBlob(part,mime,q);const url=URL.createObjectURL(blob);generated.push({blob,url,name:`carousel-${String(i+1).padStart(2,'0')}.${extensionFor(mime)}`});const card=document.createElement('article');card.className='preview-item';card.innerHTML=`<img src="${url}" alt="Carousel slide ${i+1}"><footer><strong>Slide ${i+1}</strong><button class="brut-btn brut-btn--sm" type="button" data-download="${i}">Download</button></footer>`;results.appendChild(card)}downloadAllButton.disabled=false;setStatus(`${count} slides ready · ${slideW} × ${slideH}px each.`)}catch(error){console.error(error);setStatus(error.message||'Could not split this image.')}finally{splitButton.disabled=false}}
splitButton.addEventListener('click',splitImage);results.addEventListener('click',e=>{const button=e.target.closest('[data-download]');if(!button)return;const item=generated[Number(button.dataset.download)];if(item){const a=document.createElement('a');a.href=item.url;a.download=item.name;a.click()}});downloadAllButton.addEventListener('click',async()=>{if(!generated.length)return;if(!window.JSZip){setStatus('ZIP library is unavailable. Download slides individually instead.');return}downloadAllButton.disabled=true;try{const zip=new JSZip();generated.forEach(item=>zip.file(item.name,item.blob));const blob=await zip.generateAsync({type:'blob'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='astakula-carousel-slides.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);setStatus(`ZIP ready with ${generated.length} slides.`)}catch(error){console.error(error);setStatus('Could not create the ZIP package.')}finally{downloadAllButton.disabled=false}});