const input=document.getElementById('safeInput');const dropZone=document.getElementById('dropZone');const preset=document.getElementById('safePreset');const topRange=document.getElementById('topRange');const bottomRange=document.getElementById('bottomRange');const sideRange=document.getElementById('sideRange');const topValue=document.getElementById('topValue');const bottomValue=document.getElementById('bottomValue');const sideValue=document.getElementById('sideValue');const canvas=document.getElementById('safeCanvas');const ctx=canvas.getContext('2d');const statusBox=document.getElementById('statusBox');const downloadPreview=document.getElementById('downloadPreview');const downloadOverlay=document.getElementById('downloadOverlay');const clearButton=document.getElementById('clearButton');const summary=document.getElementById('summary');let image=null;let sourceUrl='';
const presets={story:{name:'Instagram Story',w:1080,h:1920,top:250,bottom:300,side:90},reels:{name:'Instagram Reels Cover',w:1080,h:1920,top:250,bottom:300,side:90},tiktok:{name:'TikTok Vertical',w:1080,h:1920,top:220,bottom:350,side:120},shorts:{name:'YouTube Shorts',w:1080,h:1920,top:180,bottom:320,side:100},feed:{name:'Instagram Feed 4:5',w:1080,h:1350,top:72,bottom:72,side:72}};
function setStatus(message){statusBox.textContent=message}
function current(){return presets[preset.value]}
function updateLabels(){topValue.textContent=`${topRange.value}px`;bottomValue.textContent=`${bottomRange.value}px`;sideValue.textContent=`${sideRange.value}px`}
function applyPreset(){const p=current();topRange.max=Math.floor(p.h*.4);bottomRange.max=Math.floor(p.h*.45);sideRange.max=Math.floor(p.w*.3);topRange.value=p.top;bottomRange.value=p.bottom;sideRange.value=p.side;updateLabels();draw()}
function drawImageCover(targetCtx,img,w,h){const scale=Math.max(w/img.naturalWidth,h/img.naturalHeight);const dw=img.naturalWidth*scale,dh=img.naturalHeight*scale;targetCtx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh)}
function drawOverlay(targetCtx,w,h,top,bottom,side){targetCtx.save();targetCtx.fillStyle='rgba(0,0,0,.38)';targetCtx.fillRect(0,0,w,top);targetCtx.fillRect(0,h-bottom,w,bottom);targetCtx.fillRect(0,top,side,h-top-bottom);targetCtx.fillRect(w-side,top,side,h-top-bottom);targetCtx.strokeStyle='#ffffff';targetCtx.lineWidth=Math.max(4,w/270);targetCtx.setLineDash([18,14]);targetCtx.strokeRect(side,top,w-side*2,h-top-bottom);targetCtx.setLineDash([]);targetCtx.fillStyle='rgba(0,0,0,.68)';targetCtx.fillRect(side+16,top+16,285,54);targetCtx.fillStyle='#ffffff';targetCtx.font='700 28px system-ui,sans-serif';targetCtx.fillText('Suggested safe area',side+30,top+52);targetCtx.restore()}
function draw(){const p=current(),top=Number(topRange.value),bottom=Number(bottomRange.value),side=Number(sideRange.value);canvas.width=p.w;canvas.height=p.h;ctx.fillStyle='#e8e5dd';ctx.fillRect(0,0,p.w,p.h);if(image)drawImageCover(ctx,image,p.w,p.h);else{ctx.fillStyle='#111';ctx.font='700 42px system-ui,sans-serif';ctx.textAlign='center';ctx.fillText('Upload an image to preview',p.w/2,p.h/2)}drawOverlay(ctx,p.w,p.h,top,bottom,side);const safeW=Math.max(0,p.w-side*2),safeH=Math.max(0,p.h-top-bottom);summary.innerHTML=`<div><span>Canvas</span><strong>${p.w} × ${p.h}</strong></div><div><span>Safe width</span><strong>${safeW}px</strong></div><div><span>Safe height</span><strong>${safeH}px</strong></div><div><span>Preset</span><strong>${p.name}</strong></div>`;downloadPreview.disabled=!image;downloadOverlay.disabled=false}
async function setFile(file){if(!file||!file.type.startsWith('image/')||file.size>30*1024*1024){setStatus('Choose an image file up to 30 MB.');return}if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(file);const img=new Image();img.onload=()=>{image=img;draw();setStatus(`${file.name} ready · ${img.naturalWidth} × ${img.naturalHeight}px`)};img.onerror=()=>setStatus('Could not read that image.');img.src=sourceUrl}
input.addEventListener('change',()=>setFile(input.files?.[0]));dropZone.addEventListener('dragover',e=>e.preventDefault());dropZone.addEventListener('drop',e=>{e.preventDefault();setFile(e.dataTransfer.files?.[0])});document.addEventListener('paste',e=>{const file=[...(e.clipboardData?.files||[])].find(item=>item.type.startsWith('image/'));if(file)setFile(file)});preset.addEventListener('change',applyPreset);[topRange,bottomRange,sideRange].forEach(control=>control.addEventListener('input',()=>{updateLabels();draw()}));clearButton.addEventListener('click',()=>{if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl='';image=null;input.value='';draw();setStatus('Guide reset. Upload an image if you want to preview artwork.')});
function downloadCanvas(source,name){source.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)},'image/png')}
downloadPreview.addEventListener('click',()=>downloadCanvas(canvas,'astakula-safe-zone-preview.png'));downloadOverlay.addEventListener('click',()=>{const p=current(),overlay=document.createElement('canvas');overlay.width=p.w;overlay.height=p.h;const octx=overlay.getContext('2d');drawOverlay(octx,p.w,p.h,Number(topRange.value),Number(bottomRange.value),Number(sideRange.value));downloadCanvas(overlay,'astakula-safe-zone-overlay.png')});applyPreset();