const input=document.getElementById('safeInput');const dropZone=document.getElementById('dropZone');const preset=document.getElementById('safePreset');const topRange=document.getElementById('topRange');const bottomRange=document.getElementById('bottomRange');const sideRange=document.getElementById('sideRange');const topValue=document.getElementById('topValue');const bottomValue=document.getElementById('bottomValue');const sideValue=document.getElementById('sideValue');const canvas=document.getElementById('safeCanvas');const ctx=canvas.getContext('2d');const statusBox=document.getElementById('statusBox');const downloadPreview=document.getElementById('downloadPreview');const downloadOverlay=document.getElementById('downloadOverlay');const clearButton=document.getElementById('clearButton');const summary=document.getElementById('summary');const autoGuideNote=document.getElementById('autoGuideNote');const modeButtons=[...document.querySelectorAll('[data-mode]')];let image=null;let sourceUrl='';let guideMode='recommended';
const presets={story:{name:'Instagram Story',w:1080,h:1920,guides:{minimal:{top:180,bottom:220,side:54},recommended:{top:250,bottom:300,side:90},conservative:{top:320,bottom:380,side:120}}},reels:{name:'Instagram Reels Cover',w:1080,h:1920,guides:{minimal:{top:190,bottom:270,side:64},recommended:{top:270,bottom:360,side:110},conservative:{top:340,bottom:440,side:140}}},tiktok:{name:'TikTok Vertical',w:1080,h:1920,guides:{minimal:{top:180,bottom:300,side:80},recommended:{top:260,bottom:420,side:140},conservative:{top:330,bottom:500,side:175}}},shorts:{name:'YouTube Shorts',w:1080,h:1920,guides:{minimal:{top:160,bottom:260,side:70},recommended:{top:220,bottom:360,side:110},conservative:{top:300,bottom:440,side:145}}},feed:{name:'Instagram Feed 4:5',w:1080,h:1350,guides:{minimal:{top:40,bottom:40,side:40},recommended:{top:72,bottom:72,side:72},conservative:{top:110,bottom:110,side:96}}}};
function setStatus(message){statusBox.textContent=message}function current(){return presets[preset.value]}function titleCase(value){return value.charAt(0).toUpperCase()+value.slice(1)}
function updateLabels(){topValue.textContent=`${topRange.value}px`;bottomValue.textContent=`${bottomRange.value}px`;sideValue.textContent=`${sideRange.value}px`}
function syncModeButtons(){modeButtons.forEach(button=>{const active=button.dataset.mode===guideMode;button.classList.toggle('is-active',active);button.setAttribute('aria-pressed',String(active))})}
function setGuideMode(mode,{announce=true}={}){if(!['minimal','recommended','conservative'].includes(mode))return;guideMode=mode;const p=current();const values=p.guides[mode];topRange.max=Math.floor(p.h*.4);bottomRange.max=Math.floor(p.h*.45);sideRange.max=Math.floor(p.w*.3);topRange.value=values.top;bottomRange.value=values.bottom;sideRange.value=values.side;syncModeButtons();updateLabels();autoGuideNote.textContent=`${titleCase(mode)} margins applied automatically for ${p.name}.`;if(announce)setStatus(`${titleCase(mode)} guide applied for ${p.name}.`);draw()}
function applyPreset(){setGuideMode(guideMode==='custom'?'recommended':guideMode,{announce:true})}
function markCustom(){guideMode='custom';syncModeButtons();updateLabels();autoGuideNote.textContent=`Custom margins for ${current().name}. Choose a guide strength to restore automatic margins.`;setStatus(`Custom guide active for ${current().name}.`);draw()}
function drawImageCover(targetCtx,img,w,h){const scale=Math.max(w/img.naturalWidth,h/img.naturalHeight);const dw=img.naturalWidth*scale,dh=img.naturalHeight*scale;targetCtx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh)}
function drawOverlay(targetCtx,w,h,top,bottom,side){targetCtx.save();targetCtx.fillStyle='rgba(0,0,0,.38)';targetCtx.fillRect(0,0,w,top);targetCtx.fillRect(0,h-bottom,w,bottom);targetCtx.fillRect(0,top,side,h-top-bottom);targetCtx.fillRect(w-side,top,side,h-top-bottom);targetCtx.strokeStyle='#ffffff';targetCtx.lineWidth=Math.max(4,w/270);targetCtx.setLineDash([18,14]);targetCtx.strokeRect(side,top,w-side*2,h-top-bottom);targetCtx.setLineDash([]);targetCtx.fillStyle='rgba(0,0,0,.68)';targetCtx.fillRect(side+16,top+16,285,54);targetCtx.fillStyle='#ffffff';targetCtx.font='700 28px system-ui,sans-serif';targetCtx.fillText('Suggested safe area',side+30,top+52);targetCtx.restore()}
function draw(){const p=current(),top=Number(topRange.value),bottom=Number(bottomRange.value),side=Number(sideRange.value);canvas.width=p.w;canvas.height=p.h;ctx.fillStyle='#e8e5dd';ctx.fillRect(0,0,p.w,p.h);if(image)drawImageCover(ctx,image,p.w,p.h);else{ctx.fillStyle='#111';ctx.font='700 42px system-ui,sans-serif';ctx.textAlign='center';ctx.fillText('Upload an image to preview',p.w/2,p.h/2)}drawOverlay(ctx,p.w,p.h,top,bottom,side);const safeW=Math.max(0,p.w-side*2),safeH=Math.max(0,p.h-top-bottom);summary.innerHTML=`<div><span>Canvas</span><strong>${p.w} × ${p.h}</strong></div><div><span>Safe area</span><strong>${safeW} × ${safeH}</strong></div><div><span>Preset</span><strong>${p.name}</strong></div><div><span>Guide</span><strong>${guideMode==='custom'?'Custom':titleCase(guideMode)}</strong></div>`;downloadPreview.disabled=!image;downloadOverlay.disabled=false}
async function setFile(file){if(!file||!file.type.startsWith('image/')||file.size>30*1024*1024){setStatus('Choose an image file up to 30 MB.');return}if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(file);const img=new Image();img.onload=()=>{image=img;draw();setStatus(`${file.name} ready · ${img.naturalWidth} × ${img.naturalHeight}px · ${guideMode==='custom'?'Custom':titleCase(guideMode)} guide`)};img.onerror=()=>setStatus('Could not read that image.');img.src=sourceUrl}
input.addEventListener('change',()=>setFile(input.files?.[0]));dropZone.addEventListener('dragover',e=>e.preventDefault());dropZone.addEventListener('drop',e=>{e.preventDefault();setFile(e.dataTransfer.files?.[0])});document.addEventListener('paste',e=>{const file=[...(e.clipboardData?.files||[])].find(item=>item.type.startsWith('image/'));if(file)setFile(file)});preset.addEventListener('change',applyPreset);modeButtons.forEach(button=>button.addEventListener('click',()=>setGuideMode(button.dataset.mode)));[topRange,bottomRange,sideRange].forEach(control=>control.addEventListener('input',markCustom));clearButton.addEventListener('click',()=>{if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl='';image=null;input.value='';draw();setStatus(`${guideMode==='custom'?'Custom':titleCase(guideMode)} guide ready. Upload an image if you want to preview artwork.`)});
function downloadCanvas(source,name){source.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)},'image/png')}
downloadPreview.addEventListener('click',()=>downloadCanvas(canvas,'astakula-safe-zone-preview.png'));downloadOverlay.addEventListener('click',()=>{const p=current(),overlay=document.createElement('canvas');overlay.width=p.w;overlay.height=p.h;const octx=overlay.getContext('2d');drawOverlay(octx,p.w,p.h,Number(topRange.value),Number(bottomRange.value),Number(sideRange.value));downloadCanvas(overlay,'astakula-safe-zone-overlay.png')});setGuideMode('recommended',{announce:false});