const input=document.getElementById('gridInput');const dropZone=document.getElementById('dropZone');const queue=document.getElementById('queue');const grid=document.getElementById('gridPreview');const statusBox=document.getElementById('statusBox');const clearButton=document.getElementById('clearButton');const downloadButton=document.getElementById('downloadButton');let items=[];
function setStatus(message){statusBox.textContent=message}
function cleanup(item){if(item?.url)URL.revokeObjectURL(item.url)}
function addFiles(files){const images=[...files].filter(file=>file.type.startsWith('image/')&&file.size<=25*1024*1024);for(const file of images){if(items.length>=12)break;items.push({file,url:URL.createObjectURL(file)})}render();setStatus(`${items.length} image${items.length===1?'':'s'} in the preview. Top-left is position 1.`)}
function render(){queue.innerHTML='';grid.innerHTML='';items.forEach((item,index)=>{const row=document.createElement('div');row.className='queue-row';row.innerHTML=`<img src="${item.url}" alt=""><strong>${item.file.name}</strong><div class="queue-actions"><button class="brut-btn brut-btn--sm" type="button" data-action="up" data-index="${index}" ${index===0?'disabled':''}>↑</button><button class="brut-btn brut-btn--sm" type="button" data-action="down" data-index="${index}" ${index===items.length-1?'disabled':''}>↓</button><button class="brut-btn brut-btn--sm" type="button" data-action="remove" data-index="${index}">×</button></div>`;queue.appendChild(row);const tile=document.createElement('div');tile.className='grid-tile';tile.innerHTML=`<img src="${item.url}" alt="Preview position ${index+1}"><span class="tile-order">${index+1}</span>`;grid.appendChild(tile)});downloadButton.disabled=!items.length}
function swap(a,b){[items[a],items[b]]=[items[b],items[a]];render()}
queue.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(!button)return;const index=Number(button.dataset.index);if(button.dataset.action==='up'&&index>0)swap(index,index-1);if(button.dataset.action==='down'&&index<items.length-1)swap(index,index+1);if(button.dataset.action==='remove'){cleanup(items[index]);items.splice(index,1);render();setStatus(`${items.length} image${items.length===1?'':'s'} remaining.`)}});
input.addEventListener('change',()=>addFiles(input.files||[]));dropZone.addEventListener('dragover',e=>e.preventDefault());dropZone.addEventListener('drop',e=>{e.preventDefault();addFiles(e.dataTransfer.files||[])});document.addEventListener('paste',e=>{if(e.clipboardData?.files?.length)addFiles(e.clipboardData.files)});clearButton.addEventListener('click',()=>{items.forEach(cleanup);items=[];input.value='';render();setStatus('Choose images to begin.')});
function loadImage(url){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url})}
async function drawCover(ctx,img,x,y,size){const scale=Math.max(size/img.naturalWidth,size/img.naturalHeight);const w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,x+(size-w)/2,y+(size-h)/2,w,h)}
downloadButton.addEventListener('click',async()=>{if(!items.length)return;downloadButton.disabled=true;try{const cols=3;const rows=Math.ceil(items.length/cols);const tile=360,gap=4;const canvas=document.createElement('canvas');canvas.width=cols*tile+(cols-1)*gap;canvas.height=rows*tile+(rows-1)*gap;const ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);for(let i=0;i<items.length;i++){const img=await loadImage(items[i].url);const x=(i%cols)*(tile+gap),y=Math.floor(i/cols)*(tile+gap);await drawCover(ctx,img,x,y,tile)}const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Export failed.')),'image/png'));const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='astakula-grid-preview.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);setStatus(`Preview PNG exported with ${items.length} images.`)}catch(error){console.error(error);setStatus('Could not export the grid preview.')}finally{downloadButton.disabled=false}});